version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/0xdiba/go-service
    steps:
      - checkout
      - run: go test -v ./...

  publish:
    environment:
      IMAGE_NAME: 0xdiba/go-service
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image
            command: |
              docker build -t $IMAGE_NAME:latest .
        - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
                IMAGE_TAG=${CIRCLE_TAG/v/''}
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
                docker push $IMAGE_NAME:latest
                docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    docker:
            - image: hashicorp/terraform:0.12.20
    steps:
      - checkout
      - run:
          name: tf init
          command: cd ./terraform && terraform init -input=false
      - run:
          name: tf refresh
          command: cd ./terraform && terraform refresh
      - run:
          name: tf apply after determining the correct image version
          command: cd ./terraform && TF_VAR_image_version=${CIRCLE_TAG/v/''} terraform apply -auto-approve -input=false

workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - publish
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
