version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/0xdiba/go-service
    steps:
      - checkout
      - run: go test -v ./...

  publish:
    environment:
      IMAGE_NAME: 0xdiba/go-service
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image
            command: |
              docker build -t $IMAGE_NAME:latest .
        - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
                IMAGE_TAG=${CIRCLE_TAG/v/''}
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
                docker push $IMAGE_NAME:latest
                docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
